name: translator_gpt
description: Translator that uses artificial intelligence.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: 5.0.3
  flutter_bloc: 8.1.3
  dart_openai: 3.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  icons_launcher: 2.1.3
  flutter_test:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_lints: ^2.0.0

icons_launcher:
  image_path: "assets/ic_logo_border.jpg"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    web:
      enable: true

flutter:
  uses-material-design: true